// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtVE1_x-vwGU2pHYKeeSK4K5SvL5HRlPc',
    appId: '1:362611877741:web:3f23d14f626808b7099c64',
    messagingSenderId: '362611877741',
    projectId: 'cie-exams-viit',
    authDomain: 'cie-exams-viit.firebaseapp.com',
    storageBucket: 'cie-exams-viit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLuMjcHWucAOQQouIFBAElXsWz1oVybs0',
    appId: '1:362611877741:android:acdf057d6af0e38c099c64',
    messagingSenderId: '362611877741',
    projectId: 'cie-exams-viit',
    storageBucket: 'cie-exams-viit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaL6TnujWPqTNXSZTIZ0rDRTxbQHNj-Ro',
    appId: '1:362611877741:ios:0519568d46752034099c64',
    messagingSenderId: '362611877741',
    projectId: 'cie-exams-viit',
    storageBucket: 'cie-exams-viit.appspot.com',
    iosBundleId: 'com.example.cieExamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaL6TnujWPqTNXSZTIZ0rDRTxbQHNj-Ro',
    appId: '1:362611877741:ios:0519568d46752034099c64',
    messagingSenderId: '362611877741',
    projectId: 'cie-exams-viit',
    storageBucket: 'cie-exams-viit.appspot.com',
    iosBundleId: 'com.example.cieExamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtVE1_x-vwGU2pHYKeeSK4K5SvL5HRlPc',
    appId: '1:362611877741:web:d100a4e14bea0ca4099c64',
    messagingSenderId: '362611877741',
    projectId: 'cie-exams-viit',
    authDomain: 'cie-exams-viit.firebaseapp.com',
    storageBucket: 'cie-exams-viit.appspot.com',
  );
}
